# Generated by Django 4.2.3 on 2023-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
